DELETE FROM users;
DELETE FROM member;
DELETE FROM editor;
DELETE FROM reviewer;
DELETE FROM makelaar;

ALTER TABLE users DROP id_user;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE users ADD id_user int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE member DROP id_member;
ALTER TABLE member AUTO_INCREMENT = 1;
ALTER TABLE member ADD id_member int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE editor DROP id_editor;
ALTER TABLE editor AUTO_INCREMENT = 1;
ALTER TABLE editor ADD id_editor int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE reviewer DROP id_reviewer;
ALTER TABLE reviewer AUTO_INCREMENT = 1;
ALTER TABLE reviewer ADD id_reviewer int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE makelaar DROP id_makelaar;
ALTER TABLE makelaar AUTO_INCREMENT = 1;
ALTER TABLE makelaar ADD id_makelaar int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

